[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ame"
version = "0.1.1"
license = {file = "LICENSE-CODE"}
description = "Agentic Memory Evaluation Framework"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "autogen-core==0.4.3",
]

[tool.hatch.build.targets.wheel]
packages = ["src/ame"]

[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.ruff.lint]
# Allow prints in this package
ignore = ["T20"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml src"
